export interface Adaptor {
  id: string;
  name: string;
  description: string;
  category: string;
}

/**
 * OpenFn supported adaptors list.
 * Source: https://docs.openfn.org/adaptors
 */
export const adaptors: Adaptor[] = [
  { id: "arcgis", name: "ArcGIS", description: "Geospatial data and mapping", category: "GIS & Mapping" },
  { id: "asana", name: "Asana", description: "Project and task management", category: "Productivity" },
  { id: "aws-s3", name: "AWS S3", description: "Amazon cloud storage", category: "Cloud Storage" },
  { id: "azure-storage", name: "Azure Storage", description: "Microsoft Azure cloud storage", category: "Cloud Storage" },
  { id: "beyonic", name: "Beyonic", description: "Mobile money and payments", category: "Payments" },
  { id: "bigquery", name: "BigQuery", description: "Google data warehouse and analytics", category: "Data & Analytics" },
  { id: "cartodb", name: "CartoDB", description: "Location intelligence and mapping", category: "GIS & Mapping" },
  { id: "chatgpt", name: "ChatGPT", description: "OpenAI conversational AI", category: "AI & ML" },
  { id: "cht", name: "Community Health Toolkit", description: "Community health platform", category: "Health" },
  { id: "claude", name: "Claude", description: "Anthropic AI assistant", category: "AI & ML" },
  { id: "commcare", name: "CommCare", description: "Mobile data collection for frontline workers", category: "Data Collection" },
  { id: "dhis2", name: "DHIS2", description: "District Health Information System", category: "Health" },
  { id: "divoc", name: "DIVOC", description: "Digital vaccination certificates", category: "Health" },
  { id: "dynamics", name: "Microsoft Dynamics", description: "CRM and ERP platform", category: "CRM & ERP" },
  { id: "erpnext", name: "ERPNext", description: "Open-source ERP system", category: "CRM & ERP" },
  { id: "facebook", name: "Facebook", description: "Meta social platform", category: "Social & Messaging" },
  { id: "fhir", name: "FHIR", description: "Healthcare interoperability resources", category: "Health" },
  { id: "flutterwave", name: "Flutterwave", description: "African payment processing", category: "Payments" },
  { id: "gemini", name: "Gemini", description: "Google AI model", category: "AI & ML" },
  { id: "gmail", name: "Gmail", description: "Google email service", category: "Communication" },
  { id: "godata", name: "Go.Data", description: "Disease surveillance platform", category: "Health" },
  { id: "googledrive", name: "Google Drive", description: "Cloud file storage", category: "Cloud Storage" },
  { id: "googlehealthcare", name: "Google Healthcare", description: "Google Cloud Healthcare API", category: "Health" },
  { id: "googlesheets", name: "Google Sheets", description: "Cloud spreadsheet service", category: "Productivity" },
  { id: "http", name: "HTTP", description: "Generic REST API requests", category: "General" },
  { id: "ihris", name: "iHRIS", description: "Human resources for health", category: "Health" },
  { id: "khanacademy", name: "Khan Academy", description: "Educational content platform", category: "Education" },
  { id: "kobotoolbox", name: "KoBoToolbox", description: "Survey and data collection", category: "Data Collection" },
  { id: "magpi", name: "Magpi", description: "Mobile data collection", category: "Data Collection" },
  { id: "mailchimp", name: "Mailchimp", description: "Email marketing platform", category: "Communication" },
  { id: "mailgun", name: "Mailgun", description: "Email sending and management", category: "Communication" },
  { id: "maximo", name: "Maximo", description: "Asset and maintenance management", category: "Operations" },
  { id: "medicmobile", name: "Medic Mobile", description: "Community health worker platform", category: "Health" },
  { id: "mongodb", name: "MongoDB", description: "NoSQL document database", category: "Databases" },
  { id: "moodle", name: "Moodle", description: "Learning management system", category: "Education" },
  { id: "mpesa", name: "M-Pesa", description: "Mobile money service", category: "Payments" },
  { id: "msgraph", name: "Microsoft Graph", description: "Microsoft 365 API integration", category: "Productivity" },
  { id: "mssql", name: "Microsoft SQL Server", description: "Relational database", category: "Databases" },
  { id: "mysql", name: "MySQL", description: "Open-source relational database", category: "Databases" },
  { id: "odk", name: "ODK", description: "Open Data Kit form collection", category: "Data Collection" },
  { id: "odoo", name: "Odoo", description: "Open-source ERP and CRM", category: "CRM & ERP" },
  { id: "ona", name: "Ona", description: "Data collection and analytics", category: "Data Collection" },
  { id: "opencrvs", name: "OpenCRVS", description: "Civil registration system", category: "Government" },
  { id: "openelis", name: "OpenELIS", description: "Laboratory management system", category: "Health" },
  { id: "openhim", name: "OpenHIM", description: "Health interoperability middleware", category: "Health" },
  { id: "openimis", name: "openIMIS", description: "Social health protection", category: "Health" },
  { id: "openlmis", name: "OpenLMIS", description: "Logistics management system", category: "Supply Chain" },
  { id: "openmrs", name: "OpenMRS", description: "Electronic medical records", category: "Health" },
  { id: "openspp", name: "OpenSPP", description: "Social protection programs", category: "Government" },
  { id: "postgresql", name: "PostgreSQL", description: "Open-source relational database", category: "Databases" },
  { id: "powerbi", name: "Power BI", description: "Microsoft business intelligence", category: "Data & Analytics" },
  { id: "primero", name: "Primero", description: "Child protection case management", category: "Social Services" },
  { id: "rapidpro", name: "RapidPro", description: "SMS campaign and messaging", category: "Communication" },
  { id: "redis", name: "Redis", description: "In-memory data store", category: "Databases" },
  { id: "salesforce", name: "Salesforce", description: "CRM and business cloud platform", category: "CRM & ERP" },
  { id: "satusehat", name: "SATUSEHAT", description: "Indonesia health data exchange", category: "Health" },
  { id: "sftp", name: "SFTP", description: "Secure file transfer protocol", category: "General" },
  { id: "stripe", name: "Stripe", description: "Payment processing platform", category: "Payments" },
  { id: "surveycto", name: "SurveyCTO", description: "Mobile survey and data collection", category: "Data Collection" },
  { id: "tableau", name: "Tableau", description: "Data visualization platform", category: "Data & Analytics" },
  { id: "telerivet", name: "Telerivet", description: "SMS and mobile applications", category: "Communication" },
  { id: "twilio", name: "Twilio", description: "Communications platform", category: "Communication" },
  { id: "vtiger", name: "Vtiger", description: "CRM and business management", category: "CRM & ERP" },
  { id: "whatsapp", name: "WhatsApp", description: "Messaging platform", category: "Social & Messaging" },
  { id: "zoho", name: "Zoho", description: "Business software suite", category: "CRM & ERP" },
];
